---
title: "UK-vaccinations-2nd-cumulative"
author: "Vanessa Fillis"
date: "10/06/2021"
output: html_document
---

# The cumulative number in UK with a 2nd vaccine dose

## Activating packages

```{r}
library(jsonlite)
library(httr)
library(dplyr)
library(zoo)
```

## Importing the data 

```{r}
#' Extracts paginated data by requesting all of the pages
#' and combining the results.
#'
#' @param filters    API filters. See the API documentations for 
#'                   additional information.
#'                   
#' @param structure  Structure parameter. See the API documentations 
#'                   for additional information.
#'                   
#' @return list      Comprehensive list of dictionaries containing all 
#'                   the data for the given ``filter`` and ``structure`.`
get_paginated_data <- function (filters, structure) {
  
    endpoint     <- "https://api.coronavirus.data.gov.uk/v1/data"
    results      <- list()
    current_page <- 1
    
    repeat {
        httr::GET(
            url   = endpoint,
            query = list(
                filters   = paste(filters, collapse = ";"),
                structure = jsonlite::toJSON(structure, auto_unbox = TRUE),
                page      = current_page
            ),
            timeout(10)
        ) -> response
        
        # Handle errors:
        if ( response$status_code >= 400 ) {
            err_msg = httr::http_status(response)
            stop(err_msg)
        } else if ( response$status_code == 204 ) {
            break
        }
        
        # Convert response from binary to JSON:
        json_text <- content(response, "text")
        dt        <- jsonlite::fromJSON(json_text)
        results   <- rbind(results, dt$data)
        
        if ( is.null( dt$pagination$`next` ) ){
            break
        }
    
        current_page <- current_page + 1;
    }
    
    return(results)
    
}
# Create filters:
query_filters <- c(
    "areaType=overview"
)

# Create the structure as a list or a list of lists:
query_structure <- list(
    date       = "date", 
    name       = "areaName", 
    code       = "areaCode", 
    cumulative.second.dose = "cumPeopleVaccinatedSecondDoseByPublishDate"
)
vaccinations.UK <- get_paginated_data(query_filters, query_structure)
list(
  "Shape"                = dim(vaccinations.UK),
  "Data (first 3 items)" = vaccinations.UK[0:3, 0:-1]
) -> report
print(report)

```

## Formatting data frame

```{r}
vaccinations.UK <- vaccinations.UK[-c(2,3)]
```

## Exporting it 

It's ready to be uploaded to GitHub and from there linked to the Datawrapper chart. 

```{r}
write.csv(vaccinations.UK, file = "UK-vaccinations-2nd-cumulative.csv")
```

